[package]
name = "iw4-servers-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tl = "0.7.8"
ureq = { version = "2.10.1", default-features = false, features = ["tls"] }
