[build]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]

[target.x86_64-unknown-openbsd]
linker = "x86_64-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.aarch64-unknown-openbsd]
linker = "aarch64-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.i686-unknown-openbsd]
linker = "i686-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.sparc64-unknown-openbsd]
linker = "sparc64-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.riscv64gc-unknown-openbsd]
linker = "riscv64gc-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.powerpc-unknown-openbsd]
linker = "powerpc-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.powerpc64-unknown-openbsd]
linker = "powerpc64-unknown-openbsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]

[target.'cfg(target_os = "macos")']
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]

[target.'cfg(all(any(target_arch = "mips", target_arch = "mip64")), target_os = "linux")']
rustflags = [
  "-Zshare-generics=y",
  "-Copt-level=3",
  "-Clink-arg=-Wl,-O3,--strip-all,--sort-common,--as-needed,-z,relro,-z,now",
  "-Zlocation-detail=none",
]

[target.'cfg(all(any(target_arch = "i686", target_arch = "x86_64", target_arch = "i586", target_arch = "mips", target_arch = "mips64"), target_family = "unix", not(target_os = "openbsd"), not(target_os = "macos")))']
rustflags = [
  "-Zshare-generics=y",
  "-Copt-level=3",
  "-Clink-arg=-Wl,-O3,--strip-all,--sort-common,--as-needed,-z,relro,-z,now",
  "-Zlocation-detail=none",
]

[target.'cfg(all(target_os = "windows", not(target_env = "gnu"), any(target_arch = "i686", target_arch = "aarch64")))']
rustflags = [
  "-Zshare-generics=y",
  "-Copt-level=3",
  "-Clink-arg=-Wl,-O3,--discard-all,--strip-all,--sort-common,--as-needed,-z,relro,-z,now,-static",
  "-Zlocation-detail=none",
]

[target.'cfg(all(target_os = "windows", target_arch = "x86_64", not(target_env = "gnu")))']
rustflags = [
  "-Ctarget-feature=+crt-static",
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Clink-arg=-Wl,-O3,--discard-all,--strip-all,--sort-common,--as-needed,-z,relro,-z,now,-static",
  "-Zlocation-detail=none",
]
[target.aarch64-unknown-netbsd]
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
linker = "aarch64-unknown-netbsd-clang"
[target.aarch64_be-unknown-netbsd]
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
linker = "aarch64_be-unknown-netbsd-clang"
[target.armv6-unknown-netbsd-eabihf]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]
linker = "armv6-unknown-netbsd-eabihf-gcc"
[target.armv7-unknown-netbsd-eabihf]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]
linker = "armv7-unknown-netbsd-eabihf-gcc"
[target.i586-unknown-netbsd]
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
linker = "i586-unknown-netbsd-clang"
[target.i686-unknown-netbsd]
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
linker = "i686-unknown-netbsd-clang"
[target.mipsel-unknown-netbsd]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]
linker = "mipsel-unknown-netbsd-gcc"
[target.powerpc-unknown-netbsd]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]
linker = "powerpc-unknown-netbsd-gcc"
[target.sparc64-unknown-netbsd]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]
linker = "sparc64-unknown-netbsd-gcc"
[target.powerpc64-unknown-netbsd]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]
linker = "powerpc64-unknown-netbsd-gcc"

[target.aarch64-unknown-freebsd]
linker = "aarch64-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
[target.i686-unknown-freebsd]
linker = "i686-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
[target.powerpc-unknown-freebsd]
linker = "powerpc-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
[target.powerpc64-unknown-freebsd]
linker = "powerpc64-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
[target.powerpc64le-unknown-freebsd]
linker = "powerpc64le-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
[target.riscv64gc-unknown-freebsd]
linker = "riscv64gc-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
[target.x86_64-unknown-freebsd]
linker = "x86_64-unknown-freebsd-clang"
rustflags = [
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Zlocation-detail=none",
  "-Clink-arg=-fuse-ld=lld",
]
