[build]
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]

[target.'cfg(target_os = "macos")']
rustflags = ["-Copt-level=3", "-Zshare-generics=y", "-Zlocation-detail=none"]

[target.'cfg(all(any(target_arch = "mips", target_arch = "mip64")), target_os = "linux")']
rustflags = [
  "-Zshare-generics=y",
  "-Copt-level=3",
  "-Clink-arg=-Wl,-O3,--strip-all,--sort-common,--as-needed,-z,relro,-z,now",
  "-Zlocation-detail=none",
]

[target.'cfg(all(any(target_arch = "i686", target_arch = "x86_64"), target_os = "linux"))']
rustflags = [
  "-Zshare-generics=y",
  "-Copt-level=3",
  "-Clink-arg=-Wl,-O3,--discard-all,--strip-all,--sort-common,--as-needed,-z,relro,-z,now",
  "-Zlocation-detail=none",
]

[target.'cfg(all(target_os = "windows", any(target_arch = "i686", target_arch = "aarch64")))']
rustflags = [
  "-Zshare-generics=y",
  "-Copt-level=3",
  "-Clink-arg=-Wl,-O3,--discard-all,--strip-all,--sort-common,--as-needed,-z,relro,-z,now,-static",
  "-Zlocation-detail=none",
]

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))']
rustflags = [
  "-Ctarget-feature=+crt-static",
  "-Copt-level=3",
  "-Zshare-generics=y",
  "-Clink-arg=-Wl,-O3,--discard-all,--strip-all,--sort-common,--as-needed,-z,relro,-z,now,-static",
  "-Zlocation-detail=none",
]
